spring:
  application:
    name: nadosolo
  jpa:
    database: h2
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nadosolo
  h2:
    console:
      enabled: true
      path: /h2-console